<a href="https://colab.research.google.com/github/OVP2023/dataPY/blob/main/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_2_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_1_Pandas_%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2%D0%B0%D1%8F_Big_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import scipy.stats as st
import seaborn as sns
import datetime
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

In [ ]:
#Загрузите в колаб файлы по оценкам (ratings) и фильмам (movies) и создайте на их основе pandas-датафреймы
headlist=['id_user','id_item','rating','timestamp']
df_rating = pd.read_csv("https://raw.githubusercontent.com/OVP2023/dataPY/main/u.data.csv",sep="\t", header=None, names=headlist)
df_rating.head()

   id_user  id_item  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [ ]:
headlist2=['id_item','movie_title','release_date','video release_date','IMDb URL','unknown','Action','Adventure','Animation',"Children's",'Comedy','Crime','Documentary','Drama','Fantasy' ]
headlist2=headlist2+ ['Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']
df_movies = pd.read_csv("/content/u.item.csv",sep="|",encoding = "ISO-8859-1", header=None, names=headlist2)
df_movies.head()

,id_item,movie_title,release_date,video release_date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
#Средствами Pandas, используя dataframe ratings, найдите id пользователя, поставившего больше всего оценок
#ID=405
df_rating['id_user'].value_counts()

id_user
405    737
655    685
13     636
450    540
276    518
      ...
441     20
36      20
812     20
895     20
93      20
Name: count, Length: 943, dtype: int64

In [ ]:
#Оставьте в датафрейме ratings только те фильмы, который оценил данный пользователь
df_rating=df_rating[df_rating['id_user']==405]
df_rating.info()

<class 'pandas.core.frame.DataFrame'>
Index: 737 entries, 12276 to 99756
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_user    737 non-null    int64
 1   id_item    737 non-null    int64
 2   rating     737 non-null    int64
 3   timestamp  737 non-null    int64
dtypes: int64(4)
memory usage: 28.8 KB

Добавьте к датафрейму из прошлого задания  столбцы:
По жанрам. Каждый столбец - это жанр. Единицу записываем, если фильм принадлежит данному жанру и 0 - если нет,также
столбцы с общим количеством оценок от всех пользователей на фильм и суммарной оценкой от всех пользователей

In [ ]:
#через join  on='id_item'

result=df_rating.merge(df_movies,on='id_item', how='left')
result=result.drop(['movie_title', 'video release_date', 'IMDb URL', 'unknown'],	axis=1)
result.head()

,id_user,id_item,rating,timestamp,release_date,Action,Adventure,Animation,Children's,Comedy,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,405,56,4,885544911,01-Jan-1994,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,405,592,1,885548670,01-Jan-1995,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
2,405,1582,1,885548670,01-Jan-1947,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,405,171,1,885549544,01-Jan-1991,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,405,580,1,885547447,01-Jan-1995,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 737 entries, 0 to 736
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_user      737 non-null    int64
 1   id_item      737 non-null    int64
 2   rating       737 non-null    int64
 3   timestamp    737 non-null    int64
 4   Action       737 non-null    int64
 5   Adventure    737 non-null    int64
 6   Animation    737 non-null    int64
 7   Children's   737 non-null    int64
 8   Comedy       737 non-null    int64
 9   Crime        737 non-null    int64
 10  Documentary  737 non-null    int64
 11  Drama        737 non-null    int64
 12  Fantasy      737 non-null    int64
 13  Film-Noir    737 non-null    int64
 14  Horror       737 non-null    int64
 15  Musical      737 non-null    int64
 16  Mystery      737 non-null    int64
 17  Romance      737 non-null    int64
 18  Sci-Fi       737 non-null    int64
 19  Thriller     737 non-null    int64
 20  War          737 non-null    int64
 21  Western      737 non-null    int64
dtypes: int64(22)
memory usage: 126.8 KB

Для построения модели "Рекомендации оценки фильма (rating) пользователям" нужны следующие признаки:
Жанры,
(Год выхода,
Общее количество оценок,
Суммарная оценка).

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics

X=result[['Action','Adventure','Animation',"Children's",'Comedy','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']] # признаки X
y=result['rating'] # целевая переменная y

#Сформируйте X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

#Возьмите модель линейной регрессии (или любую другую для задачи регрессии)  и обучите ее на фильмах
model = LinearRegression()
model.fit(X_train, y_train)

# Коэффициенты линейной регрессии по каждому признаку
model.coef_

array([ 0.21223038, -0.1365673 , -0.09307422,  0.30061144,  0.27852195,
       -0.2261071 , -0.17972456, -0.02476654,  0.99563012,  0.6119406 ,
        0.20881027,  0.43779324,  0.4858568 ,  0.18868724, -0.02551756])

In [ ]:
#Оценка модели по метрикам R2, MAE,MSE,RMSE
y_pred = model.predict(X_test)
print(f'R2: {metrics.r2_score(y_test, y_pred)}')
print(f'MAE: {metrics.mean_absolute_error(y_test, y_pred)}')
print(f'MSE: {metrics.mean_squared_error(y_test, y_pred)}')
print(f'RMSE: {np.sqrt(metrics.mean_squared_error(y_test, y_pred))}')

R2: -0.010731199336708741
MAE: 1.0584918365060372
MSE: 1.7595303542385414
RMSE: 1.3264728999261695